---
 - hosts: sv_all
   become: yes
   tasks:
     - name: Add Apt signing key on remote server to keyring
       apt_key:
       url: https://repos.influxdata.com/influxdb.key
       keyring: /etc/apt/trusted.gpg.d/debian.gpg
       state: present
     - name: Add specified repository into sources list using specified filename.
       apt_repository:
       repo: "deb https://repos.influxdata.com/ubuntu {{ansible_distribution_release}} stable"
       state: present
       filename: influxdb.list
     - name: Install the Telegraf
       apt:
       name: telegraf
       state: present
       update_cache: yes
     - copy:
       src: "{{role_path}}/files/telegraf.conf"
       dest: /etc/telegraf/telegraf.conf
       remote_src: false
     - systemd:
       name: telegraf
       state: restarted
       enabled: true
